version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: taskist-postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=taskist
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskistdb
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
